services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rtci-app
    ports:
      - "8000:8000"
    volumes:
      - ./log:/app/log
    environment:
      - LOG_LEVEL=INFO
      # Add other environment variables your application needs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - rtci-network

networks:
  rtci-network:
    driver: bridge
