# useful information:
#   https://www.redhat.com/en/blog/navigating-linux-filesystem
#   https://stackoverflow.com/a/52827029/10634126
#   https://stackoverflow.com/a/45450456/10634126


services:

  # to trigger `python3 exec_scrapes.py` runs on container generation, excluding long scrapes
  scrapers_short:
    build:
      context: .
      dockerfile: pipeline/dockerfiles/Dockerfile_scrapers_short
    container_name: scrapers_short
    image: scrapers_short
    volumes:
      - .:/rtci
      - ~/.gitconfig:/etc/gitconfig

  # to trigger `python3 exec_scrapes.py` runs on container generation, for longer scrapes
  scrapers_long:
    build:
      context: .
      dockerfile: pipeline/dockerfiles/Dockerfile_scrapers_long
    container_name: scrapers_long
    image: scrapers_long
    volumes:
      - .:/rtci
      - ~/.gitconfig:/etc/gitconfig

  # for development and testing, `tail -F anything`
  dev:
    build:
      context: .
      dockerfile: pipeline/dockerfiles/Dockerfile_dev
    container_name: Dockerfile_dev
    image: dev
    volumes:
      - .:/rtci
      - ~/.gitconfig:/etc/gitconfig

  # to run the FBI CDE API data retrieval process
  fbi:
    build:
      context: .
      dockerfile: pipeline/dockerfiles/Dockerfile_fbi
    container_name: Dockerfile_fbi
    image: fbi
    volumes:
      - .:/rtci
      - ~/.gitconfig:/etc/gitconfig