# useful information:
#   https://www.redhat.com/en/blog/navigating-linux-filesystem
#   https://stackoverflow.com/a/52827029/10634126
#   https://stackoverflow.com/a/45450456/10634126


services:
  scrapers:
    build:
      context: .
      dockerfile: pipeline/dockerfiles/Dockerfile
    container_name: scrapers
    image: scrapers
    volumes:
      - .:/rtci
      - ~/.gitconfig:/etc/gitconfig
    command: tail -F anything