---
title: "rtci_sample_audit_vizready"
output: github_document
date: 07-09-2024
---

let's load in the sample from the collector script
```{r}
samp <- read_csv("rtci_extracted.csv")
```
function to standardize the month and year fields
```{r}
standardize_month <- function(month) {
  month_numeric <- match(tolower(month), tolower(month.abb))
  if (is.na(month_numeric)) {
    month_numeric <- match(tolower(month), tolower(month.name))
  }
  return(month_numeric)
}

# Standardize the month column and convert year to numeric
crime_data <- crime_data %>%
  mutate(
    StandardizedMonth = sapply(Month, standardize_month),
    Year = as.numeric(Year)
  )
```
filter out and check out obs with problematic month/year columns
```{r}
#let's see the bad months and years 
invalid_months <- crime_data %>%
  filter(is.na(StandardizedMonth))

invalid_years <- crime_data %>%
  filter(!grepl("^20(1[8-9]|2[0-4])$", Year))

#keep only valid sample months
crime_data <- crime_data %>%
  filter(!is.na(StandardizedMonth) & grepl("^20(1[8-9]|2[0-4])$", Year))

```
make sure the crime count categories are numeric - make a list of them first
```{r}
# Convert crime category columns to numeric, allowing for negative and positive numbers and 0
crime_categories <- c("Murder", "Rape", "Robbery", 
                  "Agg Assault", "Burglary", "Larceny", "MVT", "Arson")
crime_data <- crime_data %>%
  mutate(across(all_of(crime_categories), ~as.numeric(replace(., . == "NR", NA))))
```

```{r}

# Save observations with "NR" values for crime counts to a separate data frame
nr_observations <- crime_data %>%
  filter(if_any(all_of(crime_categories), ~is.na(.)))
```

```{r}
# Function to calculate lag time
calculate_lag_time <- function(data, crime_categories) {
  data %>%
    group_by(Agency) %>%
    arrange(Year, StandardizedMonth) %>%
    mutate(
      FirstNR = ifelse(rowSums(is.na(across(all_of(crime_categories)))) > 0,
                       Year + StandardizedMonth / 12, NA),
      FirstNR = min(FirstNR, na.rm = TRUE),
      LagTime = Year + StandardizedMonth / 12 - FirstNR
    ) %>%
    ungroup() %>%
    select(-FirstNR)
}
# Apply lag time calculation
crime_data <- calculate_lag_time(crime_data, crime_categories)
```

```{r}
# Display the cleaned and standardized data frame
print("Cleaned Crime Data:")
print(crime_data)
```

```{r}
# Display observations with invalid months
print("Observations with Invalid Months:")
print(invalid_months)
```

```{r}
# Display observations with invalid years
print("Observations with Invalid Years:")
print(invalid_years)
```

```{r}
# Display observations with "NR" values for crime counts
print("Observations with 'NR' in Crime Counts:")
print(nr_observations)
```
