name: Pulling Development into Production

on:
  schedule:
    - cron: '59 23 14 * *'  # Runs at 11:59 PM on the 14th of every month
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout production branch
      - name: Checkout production branch
        uses: actions/checkout@v3
        with:
          ref: production  # Checkout the production branch

      # Step 2: Configure Git user
      - name: Set Git user
        run: |
          git config --global user.email "dhatten@ahdatalytics.com"
          git config --global user.name "dhatte2650"

      # Step 3: Pull specific files from development into production
      - name: Pull specific files from development
        run: |
          git config pull.rebase false  # Set the pull behavior to merge
          git pull origin development --no-rebase --allow-unrelated-histories  # Allow merging unrelated histories
